---
title: "R Notebook"
output: html_notebook
---

This notebook describes 6 tests of mixing models run to estimate the proportion of OM that is autochthonous in the sediment of Harsha. 

```{r}
plot(cars)
```





# load mixture data
mixture.file <- "data/May/process/mixing_model/inputs/mixing_model_isotopes_NC_15N.csv"
mix <- load_mix_data(filename = mixture.file,
                     iso_names = c("NC", "d15N"),
                     factors = c("category", "sample"),     ### was "category" for 1, "samples" for 2 and 3, NULL for 4, "site and category" for 5
                     fac_random = c(FALSE, TRUE),       ### change this - see model #6 - was "FALSE for 1 " and changed to TRUE for 2 and 3, NULL for 4, "FALSE, TRUE" for 5
                     fac_nested = c(FALSE, TRUE),  ### NULL for 1-4, "FALSE, TRUE" for 5     
                     cont_effects = NULL)      

# load source data
source.file <- "data/May/process/mixing_model/inputs/harsha_sources_isotopes_NC_15N.csv"
source <- load_source_data(filename = source.file,
                           source_factors = NULL,
                           conc_dep = FALSE,     
                           data_type = "raw", mix)

# load discrimination file
discr.file <- "data/May/process/mixing_model/inputs/harsha_discrimination.csv"
discr <- load_discr_data(filename = discr.file, mix)

######################## define JAGS model structure ########################

model_filename <- "data/May/process/mixing_model/outputs/mixSIAR_model.txt"
resid_err <- TRUE # was TRUE for 1 and 2 and 3 and 4 and 5
process_err <- TRUE #was TRUE for 1 and 2, changed to FALSE for 3, TRUE for 4, TRUE for 5
write_JAGS_model(model_filename, resid_err, process_err, mix, source)


######################## run JAGS model ########################

# For "run", can specify length of run ("test", "very short", "short", "normal", "long", "very long", "extreme"). The chain length for "test" is 1000, "normal" is 100,000, and "extreme" is 3,000,000.
# Good idea to run the test first to check if data are loaded correctly and that the model is specified correctly.

jags.1 <- run_model(run = "normal", mix, source, discr, model_filename, alpha.prior = 1, resid_err, process_err)




######################## MixSIAR examples and vignettes ########################

browseVignettes("MixSIAR")
