---
title: "mixing model misc"
output: html_notebook
---

#### PREPARE DATA TO BE USED ####

#### Prepare sample data (mixtures)
# read in data
sample_isotope <- read.xlsx("./data/May/raw/sed_ea_isotopes_may.xlsx")
# assemble data needed for mixing model into a new dataframe 
sample_isotope_csv <- data.frame(sample = sample_isotope$sample.id, NC = sample_isotope$nc, d15N = sample_isotope$d15n_total, site = sample_isotope$site.number, core = sample_isotope$core, category = sample_isotope$zone)
# write new dataframe as csv
write.csv(sample_isotope_csv, file = "data/May/process/mixing_model/inputs/mixing_model_isotopes_NC_15N.csv", row.names = FALSE)
rm(sample_isotope)
rm(sample_isotope_csv)

#### Prepare source data
# read in data
source <- read.xlsx("data/May/process/mixing_model/inputs/harsha_sources_isotopes_conc_calc.xlsx")
# assemble source data into new dataframe
source_csv <- data.frame(Source = source$Source, d15N = source$d15N, NC = source$NC.ratio, row.names = NULL)
source_csv <- source_csv[-(30:33),]
# write new dataframe as csv
write.csv(source_csv, file = "data/May/process/mixing_model/inputs/harsha_sources_isotopes_NC_15N.csv", row.names = FALSE)
rm(source)
rm(source_csv)

#### Prepare discrimination data
discrim <- read.csv("data/May/process/mixing_model/inputs/harsha_discrimination_13C_15N.csv")
colnames(discrim)[2] <- "MeanNC"
colnames(discrim)[4] <- "SDNC"
write.csv(discrim, file = "data/May/process/mixing_model/inputs/harsha_discrimination_NC_15N.csv")
rm(discrim)




# load mixture data
mixture.file <- "data/May/process/mixing_model/inputs/mixing_model_isotopes_NC_15N.csv"
mix <- load_mix_data(filename = mixture.file,
                     iso_names = c("NC", "d15N"),
                     factors = c("category", "sample"),     ### was "category" for 1, "samples" for 2 and 3, NULL for 4, "site and category" for 5
                     fac_random = c(FALSE, TRUE),       ### change this - see model #6 - was "FALSE for 1 " and changed to TRUE for 2 and 3, NULL for 4, "FALSE, TRUE" for 5
                     fac_nested = c(FALSE, TRUE),  ### NULL for 1-4, "FALSE, TRUE" for 5     
                     cont_effects = NULL)      

# load source data
source.file <- "data/May/process/mixing_model/inputs/harsha_sources_isotopes_NC_15N.csv"
source <- load_source_data(filename = source.file,
                           source_factors = NULL,
                           conc_dep = FALSE,     
                           data_type = "raw", mix)

# load discrimination file
discr.file <- "data/May/process/mixing_model/inputs/harsha_discrimination.csv"
discr <- load_discr_data(filename = discr.file, mix)

######################## define JAGS model structure ########################

model_filename <- "data/May/process/mixing_model/outputs/mixSIAR_model.txt"
resid_err <- TRUE # was TRUE for 1 and 2 and 3 and 4 and 5
process_err <- TRUE #was TRUE for 1 and 2, changed to FALSE for 3, TRUE for 4, TRUE for 5
write_JAGS_model(model_filename, resid_err, process_err, mix, source)


######################## run JAGS model ########################

# For "run", can specify length of run ("test", "very short", "short", "normal", "long", "very long", "extreme"). The chain length for "test" is 1000, "normal" is 100,000, and "extreme" is 3,000,000.
# Good idea to run the test first to check if data are loaded correctly and that the model is specified correctly.

jags.1 <- run_model(run = "normal", mix, source, discr, model_filename, alpha.prior = 1, resid_err, process_err)




######################## MixSIAR examples and vignettes ########################

browseVignettes("MixSIAR")


